name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' 'node_modules/*'
        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_EB_APP_NAME }}
          environment_name: ${{ secrets.AWS_EB_ENVIRONMENT }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
          version_label: ${{ github.sha }}
